[42기 황수영] ADD: 포스트 스크랩 기능 구현
wecode-bootcamp-korea/42-2nd-HomeAlone-backend pull request #10
Opened 2023-03-05 09:59 UTC by fromSYHwang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 포스트 스크랩 기능 구현
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
 - 로그인한 유저만 스크랩 추가/조회/삭제 가능하도록 구현
 - 포스트에 스크랩 추가 기능 구현
 - 포스트의 로그인 유저 스크랩 여부 확인 기능 구현
 - 포스트에 스크랩 취소 기능 구현
 - 유저의 스크랩한 포스트 조회 기능 구현

<br />

## :: 테스트 결과 이미지

<img width="1582" alt="스크린샷 2023-03-05 오후 6 55 03" src="https://user-images.githubusercontent.com/120305083/222953637-a3c6214f-4ab5-44ed-a57e-fa683f6e2eaf.png">
<img width="1582" alt="스크린샷 2023-03-05 오후 6 55 25" src="https://user-images.githubusercontent.com/120305083/222953630-220f4948-bd81-4c4f-83d9-ec646975d95f.png">
<img width="1582" alt="스크린샷 2023-03-05 오후 6 55 50" src="https://user-images.githubusercontent.com/120305083/222953605-c9c61336-cbfd-4e41-90b3-1958df0656f0.png">
<img width="1582" alt="스크린샷 2023-03-05 오후 6 58 14" src="https://user-images.githubusercontent.com/120305083/222953702-df3bfcfe-8f44-41a7-b35f-0be60dcfbb04.png">
<img width="1582" alt="스크린샷 2023-03-05 오후 6 58 19" src="https://user-images.githubusercontent.com/120305083/222953705-1900061d-0b06-4067-aba1-eb54ee125c77.png">

<img width="552" alt="스크린샷 2023-03-05 오후 6 42 38" src="https://user-images.githubusercontent.com/120305083/222953500-b5bc9833-d9c5-4cbf-be0d-b7d44d8df1fa.png">
<img width="512" alt="스크린샷 2023-03-05 오후 6 43 29" src="https://user-images.githubusercontent.com/120305083/222953504-e5658792-4073-49e0-810c-b15bfdc2a310.png">

<br />

## :: 기타 질문 및 특이 사항

2023-03-06 03:28 UTC, kyeongraekim requested changes

2023-03-06 03:28 UTC, kyeongraekim commented on controllers/scrapController.js
> +const isPostScrapped = catchAsync(async (req, res) => {
- 해당 내용은 최종 출력값이 실제 데이터인가요 아니면 불리언 값일까요?
- 변수명은 불리언에 대한 내용을 담고 있어 보이는데, 건너 건너 Dao 단에서 select exist 문을 사용해보는 것을 고민해보세요~

2023-03-06 05:01 UTC, fromSYHwang commented on controllers/scrapController.js
> +const isPostScrapped = catchAsync(async (req, res) => {
최종 출력값은 데이터 scrapId 입니다. 그에 맞춰 함수명을 getScrapIdByPostId 로 수정했습니다!

2023-03-06 07:19 UTC, kyeongraekim commented on controllers/scrapController.js
> +const isPostScrapped = catchAsync(async (req, res) => {
- 네 변수명을 바꾸는 것이 더 클린하게 보이네요! 그렇다면 혹시 getScrapIdByPostId는 어떠한 API 통신 시 필요한 부분인지 코멘트 남겨주실 수 있으실까요?

2023-03-06 08:11 UTC, fromSYHwang commented on controllers/scrapController.js
> +const isPostScrapped = catchAsync(async (req, res) => {
포스트 상세 페이지에서 scrapId 존재 여부를 확인하고, scrapId가 존재할 경우 프론트에서 화면에 스크랩 한 포스트라는 표시를 띄우고 스크랩 삭제 API에서 해당 scrapId를 받아 스크랩 삭제 기능이 구현 가능하도록 통신할 때 사용할 예정입니다.

2023-03-07 02:00 UTC, fromSYHwang commented
스크랩 여부 확인 변경 - 따로 엔드포인트를 만들지 않고, /posts 의 포스트 상세 페이지를 get 할 때 토큰을 받아 isPostScrapped 함수를 호출하고 true/false 를 반환한 후 서비스단에서 포스트 디테일 data에 isScrapped 키를 추가하도록 변경했습니다!

2023-03-07 06:48 UTC, kyeongraekim approved these changes
LGTM@!~

2023-03-07 06:48 UTC, merged