[42기 황수영] ADD: 포스트 작성 기능 구현
wecode-bootcamp-korea/42-2nd-HomeAlone-backend pull request #8
Opened 2023-03-05 08:15 UTC by fromSYHwang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 포스트 작성 기능 구현
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
 - 로그인한 사용자만 작성할 수 있도록 로그인 미들웨어와 연결하여 글쓰기 구현
 - aws-sdk, multer, multer-s3 모듈을 활용해 AWS S3에 파일 업로드 기능 구현
 - 포스트 작성 중 에러 발생 시 S3에 업로드한 이미지를 삭제하는 기능 구현
 - posts, post_images, image_coordinates 테이블에 트랜잭션을 이용해 포스트 데이터를 저장하는 기능 구현

<br />

## :: 테스트 결과 이미지
<img width="1582" alt="스크린샷 2023-03-05 오후 4 50 50" src="https://user-images.githubusercontent.com/120305083/222949395-fdeebd4e-5371-4fdc-afc1-553fcb5cc6db.png">
<img width="1582" alt="스크린샷 2023-03-05 오후 4 45 55" src="https://user-images.githubusercontent.com/120305083/222949386-6e71e012-3d5a-4ef8-b268-b0f43fc29a4e.png">

<br />

## :: 기타 질문 및 특이 사항

2023-03-06 03:23 UTC, kyeongraekim requested changes

2023-03-06 03:23 UTC, kyeongraekim commented on utils/imageUploader.js
> +    cb(null, `${Date.now().toString() + file.originalname}`);
- S3에 업로드 되는 파일 루트는 중복되어서는 안됩니다. 따라서 uuid4 와 같은 임의의 난수를 파일 명을 작성할 때 추가로 기입해서 업로드되게 설정해주세요~

2023-03-06 03:23 UTC, kyeongraekim commented on middlewares/auth.js
> +  console.log(decode);
- 불필요한 콘솔로깅을 삭제해주세요~

2023-03-06 03:23 UTC, kyeongraekim commented on models/postQueryBuilder.js
> +  lovely: 3,
- 상수값임으로 컨벤션에 맞게 모두 대문자로 변경해주세요!

2023-03-06 03:23 UTC, kyeongraekim commented on models/postQueryBuilder.js
> +const roomStyles = Object.freeze({
- 해당 내용은 enum의 의미를 지니고 있는 고정 객체임을 드러낼 수 있게 roomStyleEnum 정도로 변경해주세요!

2023-03-06 03:23 UTC, kyeongraekim commented on models/postQueryBuilder.js
> +  lovely: 3,
- 외부에서 들어온 값과 키 매핑을 하기 때문에 소문자로 들어온 내용을 대문자로 어떻게 치환할 수 있을지 고민해보세요!

2023-03-07 06:47 UTC, kyeongraekim requested changes

2023-03-07 06:47 UTC, kyeongraekim commented on models/postDao.js
> +        roomStyleEnum[postData.type],
- 이 부분은 혹시 프론트에서 대문자로 전달하는 부분일까요?

2023-03-07 06:57 UTC, fromSYHwang commented on models/postDao.js
> +        roomStyleEnum[postData.type],
type="vintage" 처럼 소문자로 받은 뒤 controller 단에서 service 단으로 넘길 때 type: type.toUpperCase()로 대문자로 변환해 넘기고 있습니다!

2023-03-07 07:10 UTC, kyeongraekim commented on models/postDao.js
> +        roomStyleEnum[postData.type],
넵 알겠습니다! 컨플릭트 해결해주시면 머지 진행하겠습니다~

2023-03-07 07:40 UTC, kyeongraekim approved these changes
LGTM!~

2023-03-07 07:40 UTC, merged